DAPI-211 Set Oracle VPD client identifier on connection
ministryofjustice/hmpps-delius-api pull request #159
Opened 2021-10-26 19:01 UTC by marcus-bcl

To enable data authorisation based on the authenticated user's linked datasets/providers.

Depends on https://github.com/ministryofjustice/hmpps-delius-pipelines/pull/356

2021-11-03 15:40 UTC, marcus-bcl commented on src/test/kotlin/uk/gov/justice/digital/hmpps/deliusapi/integration/v1/contact/CreateContactTest.kt
> -  fun `Attempting to create contact for unauthorized provider`() {
This isn't really a valid scenario any more for the integration tests, as they run against a H2 database which doesn't implement VPD.  Also both of these removed tests were based on the provider field (or the manager provider field) in the request, rather than testing against where the offender is currently allocated to - so weren't checking the right thing anyway.

If you call the API as a user without VPD access to the offender (or event etc), then the API will return a 404 as the DB will respond as if it doesn't exist.

2021-12-03 12:31 UTC, mxco86 requested changes

2021-12-03 12:31 UTC, mxco86 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/service/contact/ContactService.kt
> -  @ProviderRequestAuthority
I think if we're removing the provider check we should also remove the feature flag on the VPD. I can't envisage a situation where we would flag this off

2021-12-20 16:43 UTC, mxco86 approved these changes
👍

2022-01-06 15:36 UTC, axle-h approved these changes

2022-01-06 15:37 UTC, merged