fix: manager team & staff are optional
ministryofjustice/hmpps-delius-api pull request #59
Opened 2021-03-01 13:11 UTC by axle-h

2021-03-01 16:45 UTC, axle-h commented
Also includes [DAPI-93](https://jira.engineering-dev.probation.hmpps.dsd.io/browse/DAPI-93)

2021-03-01 16:54 UTC, axle-h commented on src/test/kotlin/uk/gov/justice/digital/hmpps/deliusapi/integration/IntegrationTestBase.kt
> -  }
I tried a few things but ended up giving up with integration testing auditing.
Issue is that there's no canonical primary key on the table so just like Delius, we tagged the datetime up instead. Hibernate is doing weird things with this. It's either not writing audit records that fall on the same second or when selecting it is overwriting results from it's local cache. In the worst case we're replicating Delius behaviour so I think it's fine to just drop this for now. Maybe look at raw JDBC queries for auditing at some point. Yay.

2021-03-02 12:29 UTC, electrified requested changes
The team and staff bits look OK, but less sure about the security parts and think we should try and leverage spring security more.

Possibly split into 2 PRs?

2021-03-02 12:29 UTC, electrified commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/entity/ProviderUser.kt
> +data class ProviderUserIdentity(
I wasn't expecting any security changes in this PR based on the title! :) Which JIRA are these bits for?

2021-03-02 12:29 UTC, electrified commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/service/contact/ContactService.kt
> +    securityUserContext.grantProvider(provider.id)
I feel like these could get out of control if we have to litter them all over the codebase.

See later comment re Spring Security annotations.

2021-03-02 12:29 UTC, electrified commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/service/security/SecurityUserContext.kt
> +  fun grantProvider(providerId: Long) {
This feels like we're implementing our own security system in parallel with spring security.

The check itself seems fine, but can we wrap it up in a way so we can just annotate service methods with appropriate spring security annotations?

https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/authorization.html#access-control-using-preauthorize-and-postauthorize

The question then becomes at what level to add the annotations.. Might have to do some restructuring?

2021-03-02 12:45 UTC, axle-h commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/service/security/SecurityUserContext.kt
> +  fun grantProvider(providerId: Long) {
Definitely agree, newish to Spring so missed this one. Problem here is that the provider is retrieved and saved in one method. Maybe be ok to repeat this though and the security check (however it's implemented) returns ok when the provider does not exist - the service method can then throw. The won't matter where it's annotated then - although maybe be best to be on the request DTO if possible. This will select the provider twice but doesn't seem like an issue,.

2021-03-02 12:45 UTC, axle-h commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/entity/ProviderUser.kt
> +data class ProviderUserIdentity(
I'll split this off

2021-03-02 13:10 UTC, axle-h commented
Removed commit containing security work, will reimplement with Spring security in a followup PR

2021-03-02 14:21 UTC, electrified approved these changes

2021-03-02 14:22 UTC, merged