feat: failure to comply
ministryofjustice/hmpps-delius-api pull request #79
Opened 2021-03-19 14:40 UTC by axle-h

2021-03-22 15:37 UTC, electrified approved these changes
I've not spotted anything that looks wrong, but this could do with multiple reviews as it is a complex change.

2021-03-22 16:46 UTC, axle-h commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/entity/Contact.kt
> +  var linkedContact: Contact? = null,
yeah I agree, it helps to be explicit and break the build by default on entity changes. Not sure what you mean by the data class hangover though as we're still using constructor properties?
There's loads of clean up to do with entity fields like this (eg non-nullable properties) and Id prefer to choose an approach for all entities and apply in one big refactor PR.

2021-03-22 16:56 UTC, electrified commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/entity/Contact.kt
> +  var linkedContact: Contact? = null,
Sounds like a plan - yep agree something to do separately from functional changes.

2021-03-23 14:16 UTC, MichaelWetherallBCL requested changes

2021-03-23 14:30 UTC, axle-h commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/repository/ContactRepository.kt
> +      "and c.type.nationalStandardsContact = true and (:lastResetDate is null or c.date >= :lastResetDate)"
My assumption was the Where clause on Contact would have covered this, I'll double check that is applied in this case

2021-03-23 15:26 UTC, axle-h commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/service/contact/ContactBreachService.kt
> +        val latestBreachEnd = contactRepository.findAllBreachDates(event.id, BREACH_END_CODES)
Yeah looks like Delius checks both event breach end date & date & start time from latest breach end contact rather than the fallback we have here.
https://github.com/ministryofjustice/delius/blob/908670ffa5dc02d3dafdd0f2af57feac01fb21fa/NDelius-ejb/src/main/java/uk/co/bconline/ndelius/service/contactlog/ContactServiceBean.java#L3158
It's also quite weird that for one check it combines the event start time with the breach end date on the event... I don't really understand what the original intention here was. Maybe this entire check can be broken down into:
```kotlin
val latestBreachEnd = maxOrNull(event.breachEnd, latestBreachEndContactStartDateTime)
if (latestBreachEnd == null || contactStartDateTime > latestBreachEnd) event.inBreach = true
```
I think that might replicate what Delius is doing without porting over a mess.

2021-03-23 15:52 UTC, axle-h commented on src/main/kotlin/uk/gov/justice/digital/hmpps/deliusapi/repository/ContactRepository.kt
> +      "and c.type.nationalStandardsContact = true and (:lastResetDate is null or c.date >= :lastResetDate)"
Yeah the Where clause is applied, e.g. this is the query that's generated by ContactRepository.countEnforcementUnderReview

```sql
select count(contact0_.contact_id) as col_0_0_
from contact contact0_
cross join r_contact_type contacttyp1_
where ( contact0_.SOFT_DELETED = 0)
  and contact0_.contact_type_id=contacttyp1_.contact_type_id
  and contact0_.event_id=?
  and contacttyp1_.code=?
  and (contact0_.contact_outcome_type_id is null)
   and (? is null or contact0_.contact_date>=?)
```

2021-03-24 09:35 UTC, MichaelWetherallBCL approved these changes

2021-03-24 09:37 UTC, merged